In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

### Loading the dataset

In [3]:
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_columns', None)

In [6]:
df = pd.read_csv('IMDB_Movies.csv')
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [7]:
df.shape

(5043, 28)

In [66]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews          object
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

### Checking the null values

In [5]:
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          20
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [21]:
df.isnull().sum() / len(df) * 100

color                         0.376760
director_name                 0.000000
num_critic_for_reviews        0.991473
duration                      0.297442
director_facebook_likes       2.062265
actor_3_facebook_likes        0.456078
actor_2_name                  0.257783
actor_1_facebook_likes        0.138806
gross                        17.529248
genres                        0.000000
actor_1_name                  0.138806
movie_title                   0.000000
num_voted_users               0.000000
cast_total_facebook_likes     0.000000
actor_3_name                  0.456078
facenumber_in_poster          0.257783
plot_keywords                 3.033908
movie_imdb_link               0.000000
num_user_for_reviews          0.396589
language                      0.277613
country                       0.000000
content_rating                6.008328
budget                        9.756098
title_year                    2.141582
actor_2_facebook_likes        0.257783
imdb_score                    0.000000
aspect_ratio                  6.523895
movie_facebook_likes          0.000000
dtype: float64

### We can't do any imputation on Director's Name, Actor's Name and Country, thats why we replacing null value with 'Unknown'.

In [10]:
df['director_name'].fillna('Unknown', inplace=True)

In [11]:
df['director_name'].isnull().sum()

0

In [13]:
df['director_name'].nunique()

2399

In [45]:
df['actor_1_name'].fillna('Unknown', inplace=True)

In [46]:
df['actor_1_name'].isnull().sum()

0

In [14]:
df['director_name'][df['country'].isnull()]

4               Doug Walker
279     Christopher Barnard
2370                Unknown
3397                Unknown
4021      Daniel Petrie Jr.
Name: director_name, dtype: object

In [15]:
df['country'].fillna('Unknown', inplace=True)

In [16]:
df['country'].isnull().sum()

0

### As the null percentage of the duration is very low (0.3%) we are imputing with median value

In [22]:
df['duration'].fillna(df['duration'].median(), inplace=True)

In [23]:
df['duration'].isnull().sum()

0

In [28]:
gross_median = df.groupby(['country'])['gross'].median()

In [29]:
gross_median

country
Afghanistan              1127331.0
Argentina                1221261.0
Aruba                   10076136.0
Australia               17356110.0
Bahamas                        NaN
Belgium                   680566.5
Brazil                    375723.0
Bulgaria                       NaN
Cambodia                       NaN
Cameroon                   32631.0
Canada                   6854620.0
Chile                   12188642.0
China                     190666.0
Colombia                 6517198.0
Czech Republic           1206135.0
Denmark                   778565.0
Dominican Republic             NaN
Egypt                          NaN
Finland                   611709.0
France                   4291965.0
Georgia                    17149.0
Germany                 20978074.5
Greece                   1908995.5
Hong Kong                6594136.0
Hungary                 11687595.5
Iceland                    15897.0
India                     888047.5
Indonesia                4105123.0
Iran                      962701.0
Ireland                  3594458.0
Israel                   1219624.0
Italy                    2835886.0
Japan                   10037390.0
Kenya                          NaN
Kyrgyzstan                     NaN
Libya                          NaN
Mexico                   5242385.5
Netherlands               713413.0
New Line                 6712451.0
New Zealand             30465398.0
Nigeria                        NaN
Norway                    283044.0
Official site           20218921.0
Pakistan                       NaN
Panama                         NaN
Peru                    57362581.0
Philippines                70071.0
Poland                    713000.5
Romania                  9100986.5
Russia                   3594560.0
Slovakia                       NaN
Slovenia                       NaN
South Africa            45089048.0
South Korea               940407.5
Soviet Union                   NaN
Spain                    1048525.0
Sweden                    181655.0
Switzerland                    NaN
Taiwan                  64340682.0
Thailand                  454255.0
Turkey                         NaN
UK                      13401683.0
USA                     32178777.0
United Arab Emirates           NaN
Unknown                        NaN
West Germany            11433134.0
Name: gross, dtype: float64

### We imputed null values in 'Gross' by grouping countries

In [40]:
gross_median = df.groupby('country')['gross'].median()
for country in df['country'].unique():
    country_mask = df['country'] == country
    df.loc[country_mask, 'gross'] = df.loc[country_mask, 'gross'].fillna(gross_median[country])

In [41]:
df['gross'].isnull().sum()

24

In [42]:
df['gross'].isnull().sum() / len(df) * 100

0.4759071980963712

In [43]:
df['gross'].fillna(df['gross'].median(), inplace=True)

In [44]:
df['gross'].isnull().sum()

0

### We treated the language null by grouping country

In [48]:
lang_mode = df.groupby('country')['language'].apply(lambda x: x.mode().iloc[0])

In [49]:
lang_mode

country
Afghanistan                   Dari
Argentina                  Spanish
Aruba                      English
Australia                  English
Bahamas                    English
Belgium                    English
Brazil                  Portuguese
Bulgaria                   English
Cambodia                   English
Cameroon                   English
Canada                     English
Chile                      English
China                     Mandarin
Colombia                   Spanish
Czech Republic             English
Denmark                    English
Dominican Republic         Spanish
Egypt                       Arabic
Finland                     French
France                     English
Georgia                    English
Germany                    English
Greece                     English
Hong Kong                Cantonese
Hungary                    English
Iceland                  Icelandic
India                        Hindi
Indonesia               Indonesian
Iran                       Persian
Ireland                    English
Israel                      Hebrew
Italy                      English
Japan                     Japanese
Kenya                      Swahili
Kyrgyzstan                 English
Libya                      English
Mexico                     Spanish
Netherlands                  Dutch
New Line                   English
New Zealand                English
Nigeria                    English
Norway                     English
Official site              English
Pakistan                      Urdu
Panama                     English
Peru                       English
Philippines                English
Poland                      Polish
Romania                    English
Russia                     Russian
Slovakia                   English
Slovenia                 Slovenian
South Africa               English
South Korea                 Korean
Soviet Union               Russian
Spain                      English
Sweden                     Swedish
Switzerland                English
Taiwan                    Mandarin
Thailand                      Thai
Turkey                      Arabic
UK                         English
USA                        English
United Arab Emirates        Arabic
Unknown                    English
West Germany                German
Name: language, dtype: object

In [50]:
for country in df['country'].unique():
    country_mask = df['country'] == country
    df.loc[country_mask, 'language'] = df.loc[country_mask, 'language'].fillna(lang_mode[country])

In [51]:
df.language.isnull().sum()

0

In [ ]:
df['content_rating'].ffill(inplace=True)

In [59]:
df['content_rating'].isnull().sum()

0

### Actually, We have to treat the 'Budget' by grouping country and genres but we can't explode genres because the same value will end up in same value, thats why we are grouping with country only

In [60]:
budget_mean = df.groupby('country')['budget'].mean()

In [61]:
budget_mean

country
Afghanistan             4.600000e+04
Argentina               1.425000e+06
Aruba                   3.500000e+07
Australia               3.117211e+07
Bahamas                 5.000000e+06
Belgium                 2.450000e+07
Brazil                  4.171429e+06
Bulgaria                7.000000e+06
Cambodia                         NaN
Cameroon                         NaN
Canada                  1.479846e+07
Chile                   2.600000e+07
China                   6.221900e+07
Colombia                3.000000e+06
Czech Republic          4.881667e+07
Denmark                 1.392222e+07
Dominican Republic      5.000000e+05
Egypt                   1.500000e+06
Finland                 3.850000e+06
France                  3.067203e+07
Georgia                 2.000000e+07
Germany                 3.338900e+07
Greece                  1.800000e+07
Hong Kong               2.487333e+07
Hungary                 1.260000e+09
Iceland                 6.900000e+06
India                   9.797336e+07
Indonesia               1.100000e+06
Iran                    3.672500e+06
Ireland                 1.239875e+07
Israel                  1.150000e+06
Italy                   1.306750e+07
Japan                   3.505960e+08
Kenya                   1.500000e+04
Kyrgyzstan              1.400000e+06
Libya                   3.500000e+07
Mexico                  5.508484e+06
Netherlands             1.001000e+07
New Line                9.000000e+07
New Zealand             8.152692e+07
Nigeria                 7.500000e+06
Norway                  2.088750e+07
Official site           1.500000e+07
Pakistan                1.000000e+06
Panama                  2.000000e+07
Peru                    4.500000e+07
Philippines             7.000000e+03
Poland                  2.400000e+06
Romania                 4.439500e+06
Russia                  1.727000e+07
Slovakia                         NaN
Slovenia                5.000000e+05
South Africa            1.575000e+07
South Korea             1.383960e+09
Soviet Union            1.000000e+06
Spain                   4.281667e+07
Sweden                  1.680000e+07
Switzerland             1.166667e+07
Taiwan                  1.500000e+07
Thailand                2.272500e+08
Turkey                  8.300000e+06
UK                      2.766607e+07
USA                     3.575599e+07
United Arab Emirates    1.250000e+05
Unknown                 3.500000e+06
West Germany            2.050000e+07
Name: budget, dtype: float64

In [62]:
for country in df['country'].unique():
    country_mask = df['country'] == country
    df.loc[country_mask, 'budget'] = df.loc[country_mask, 'budget'].fillna(budget_mean[country])

In [63]:
df['budget'].isnull().sum()

3

In [64]:
df['budget'].fillna(df['budget'].median(), inplace=True)

In [65]:
df['budget'].isnull().sum()

0

 ### We can't do any imputation on Year, thats why we replacing null value with 'Unknown'.

In [67]:
df['title_year'].fillna('Unknown', inplace=True)

In [69]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews          object
language                      object
country                       object
content_rating                object
budget                       float64
title_year                    object
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [76]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [78]:
df['genres'] = df['genres'].str.split('|')

In [79]:
explode_df = df.explode('genres')

In [80]:
explode_df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Adventure,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Fantasy,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Adventure,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Adventure,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

In [93]:
explode_df.nunique()

color                           2
director_name                2399
num_critic_for_reviews        528
duration                      191
director_facebook_likes       435
actor_3_facebook_likes        906
actor_2_name                 3032
actor_1_facebook_likes        878
gross                        4050
genres                         26
actor_1_name                 2098
movie_title                  4917
num_voted_users              4826
cast_total_facebook_likes    3978
actor_3_name                 3521
facenumber_in_poster           19
plot_keywords                4760
movie_imdb_link              4919
num_user_for_reviews          955
language                       46
country                        66
content_rating                 18
budget                        462
title_year                     92
actor_2_facebook_likes        917
imdb_score                     78
aspect_ratio                   22
movie_facebook_likes          876
dtype: int64

In [91]:
explode_df.shape

(14504, 28)

In [92]:
explode_df.to_excel('IMDB.xlsx')

### A. Movie Genre Analysis: Analyze the distribution of movie genres and their impact on the IMDB score..

### Task: Determine the most common genres of movies in the dataset. Then, for each genre, calculate descriptive statistics (mean, median, mode, range, variance, standard deviation) of the IMDB scores.

In [81]:
def calc_range(series=df['imdb_score']):
    return series.max() - series.min()


task_a = explode_df.groupby('genres').agg({'imdb_score': ['mean', 'median', 'min', 'max', calc_range, 'var', 'std']})

In [83]:
task_a.head().reset_index()

      genres imdb_score
                   mean median  min  max calc_range       var       std
0     Action   6.239896    6.3  1.7  9.1        7.4  1.251792  1.118835
1  Adventure   6.441170    6.6  1.9  8.9        7.0  1.279605  1.131196
2  Animation   6.576033    6.7  1.7  8.6        6.9  1.298676  1.139595
3  Biography   7.150171    7.2  4.5  8.9        4.4  0.522029  0.722516
4     Comedy   6.195246    6.3  1.7  9.5        7.8  1.189657  1.090714

In [86]:
task_a.to_excel('TaskA.xlsx')

In [87]:
task_a

            imdb_score
                  mean median  min  max calc_range       var       std
genres
Action        6.239896   6.30  1.7  9.1        7.4  1.251792  1.118835
Adventure     6.441170   6.60  1.9  8.9        7.0  1.279605  1.131196
Animation     6.576033   6.70  1.7  8.6        6.9  1.298676  1.139595
Biography     7.150171   7.20  4.5  8.9        4.4  0.522029  0.722516
Comedy        6.195246   6.30  1.7  9.5        7.8  1.189657  1.090714
Crime         6.564792   6.60  2.4  9.3        6.9  1.053613  1.026456
Documentary   7.180165   7.40  1.6  8.7        7.1  1.116270  1.056537
Drama         6.763763   6.90  2.0  9.3        7.3  0.916527  0.957354
Family        6.245055   6.40  1.7  8.7        7.0  1.443838  1.201598
Fantasy       6.307049   6.40  1.7  8.9        7.2  1.347192  1.160686
Film-Noir     7.633333   7.65  7.1  8.2        1.1  0.186667  0.432049
Game-Show     2.900000   2.90  2.9  2.9        0.0       NaN       NaN
History       7.083575   7.20  2.0  8.9        6.9  0.788370  0.887902
Horror        5.843540   5.90  2.2  8.7        6.5  1.277959  1.130469
Music         6.410280   6.60  1.6  8.5        6.9  1.389659  1.178838
Musical       6.507576   6.70  2.1  8.5        6.4  1.502385  1.225718
Mystery       6.486400   6.60  2.2  8.6        6.4  1.189755  1.090759
News          7.533333   7.40  7.1  8.1        1.0  0.263333  0.513160
Reality-TV    4.750000   4.75  2.9  6.6        3.7  6.845000  2.616295
Romance       6.450587   6.50  2.1  8.6        6.5  0.992086  0.996035
Sci-Fi        6.281818   6.40  1.9  8.8        6.9  1.466075  1.210816
Short         6.380000   6.50  5.2  7.1        1.9  0.557000  0.746324
Sport         6.606044   6.80  2.0  8.7        6.7  1.214273  1.101940
Thriller      6.314245   6.40  2.2  9.0        6.8  1.111620  1.054334
War           7.070423   7.10  2.7  8.6        5.9  0.765112  0.874707
Western       6.689691   6.80  3.8  8.9        5.1  1.086768  1.042481

In [89]:
task_a.fillna(0, inplace=True)

In [90]:
task_a

            imdb_score
                  mean median  min  max calc_range       var       std
genres
Action        6.239896   6.30  1.7  9.1        7.4  1.251792  1.118835
Adventure     6.441170   6.60  1.9  8.9        7.0  1.279605  1.131196
Animation     6.576033   6.70  1.7  8.6        6.9  1.298676  1.139595
Biography     7.150171   7.20  4.5  8.9        4.4  0.522029  0.722516
Comedy        6.195246   6.30  1.7  9.5        7.8  1.189657  1.090714
Crime         6.564792   6.60  2.4  9.3        6.9  1.053613  1.026456
Documentary   7.180165   7.40  1.6  8.7        7.1  1.116270  1.056537
Drama         6.763763   6.90  2.0  9.3        7.3  0.916527  0.957354
Family        6.245055   6.40  1.7  8.7        7.0  1.443838  1.201598
Fantasy       6.307049   6.40  1.7  8.9        7.2  1.347192  1.160686
Film-Noir     7.633333   7.65  7.1  8.2        1.1  0.186667  0.432049
Game-Show     2.900000   2.90  2.9  2.9        0.0  0.000000  0.000000
History       7.083575   7.20  2.0  8.9        6.9  0.788370  0.887902
Horror        5.843540   5.90  2.2  8.7        6.5  1.277959  1.130469
Music         6.410280   6.60  1.6  8.5        6.9  1.389659  1.178838
Musical       6.507576   6.70  2.1  8.5        6.4  1.502385  1.225718
Mystery       6.486400   6.60  2.2  8.6        6.4  1.189755  1.090759
News          7.533333   7.40  7.1  8.1        1.0  0.263333  0.513160
Reality-TV    4.750000   4.75  2.9  6.6        3.7  6.845000  2.616295
Romance       6.450587   6.50  2.1  8.6        6.5  0.992086  0.996035
Sci-Fi        6.281818   6.40  1.9  8.8        6.9  1.466075  1.210816
Short         6.380000   6.50  5.2  7.1        1.9  0.557000  0.746324
Sport         6.606044   6.80  2.0  8.7        6.7  1.214273  1.101940
Thriller      6.314245   6.40  2.2  9.0        6.8  1.111620  1.054334
War           7.070423   7.10  2.7  8.6        5.9  0.765112  0.874707
Western       6.689691   6.80  3.8  8.9        5.1  1.086768  1.042481